FROM frolvlad/alpine-python3:latest

MAINTAINER jlsche <jlsche@lingtelli.com.com>

#RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pymongo
#RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple flask

RUN pip install pymongo
RUN pip install flask

ADD volume /code	
WORKDIR /code


